class CfgPatches
{
	class prazv_vanilla_retex
	{
		author="prazv";
		version="";
		units[]=
		{
			"B_Multitarn_soldier_F",
			"B_m84_soldier_F",
			"B_wz93_soldier_F",
			"B_wz93_2_soldier_F",
			"B_rodpm_soldier_F",
			"B_mdu10_soldier_F",
			"B_cropat_soldier_F",
			"Vest_V_CarrierRigKBT_01_light_multitarn_F",
			"Vest_V_CarrierRigKBT_01_light_m84_F",
			"Vest_V_CarrierRigKBT_01_light_wz93_F",
			"Vest_V_CarrierRigKBT_01_light_mdu10_F",
			"Vest_V_CarrierRigKBT_01_light_rodpm_F",
			"Vest_V_CarrierRigKBT_01_light_cropat_F",
			"B_AssaultPack_multitarn",
			"B_AssaultPack_rodpm",
			"B_AssaultPack_m84",
			"B_AssaultPack_wz93",
			"B_AssaultPack_cropat",
			"B_AssaultPack_mdu10"
		};
		weapons[]=
		{
			"przv_U_B_Multitarn",
			"przv_U_B_m84",
			"przv_U_B_wz93",
			"prazv_U_B_rodpm",
			"prazv_U_B_mdu10",
			"prazv_U_B_wz93_2",
			"prazv_U_B_cropat",
			"V_CarrierRigKBT_01_light_multitarn_F",
			"V_CarrierRigKBT_01_light_m84_F",
			"V_CarrierRigKBT_01_light_rodpm_F",
			"V_CarrierRigKBT_01_light_wz93_F",
			"V_CarrierRigKBT_01_light_mdu10_F",
			"V_CarrierRigKBT_01_light_cropat",
			"H_HelmetB_plain_multitarn",
			"H_HelmetB_plain_rodpm",
			"H_HelmetB_plain_wz93",
			"H_HelmetB_plain_mdu10",
			"H_HelmetB_plain_m84",
			"H_HelmetB_plain_cropat",
			"H_HelmetSpecB_multitarn",
			"H_HelmetSpecB_rodpm",
			"H_HelmetSpecB_wz93",
			"H_HelmetSpecB_mdu10",
			"H_HelmetSpecB_m84",
			"H_HelmetSpecB_cropat",
			"H_HelmetHBK_headset_multitarn_F",
			"H_HelmetHBK_headset_rodpm_F",
			"H_HelmetHBK_headset_m84_F",
			"H_HelmetHBK_headset_mdu10_F",
			"H_HelmetHBK_headset_wz93_F",
			"H_HelmetHBK_headset_cropat_F",
			"H_HelmetHBK_multitarn_F",
			"H_HelmetHBK_rodpm_F",
			"H_HelmetHBK_m84_F",
			"H_HelmetHBK_mdu10_F",
			"H_HelmetHBK_wz93_F",
			"H_HelmetHBK_cropat_F"
		};
		requiredVersion="1";
		requiredAddons[]=
		{
			"A3_Characters_F",
			"A3_Characters_F_Beta",
			"A3_Characters_F_Gamma",
			"A3_Characters_F_EPA",
			"A3_Characters_F_EPB",
		};
	};
};